//
// Created by connor on 12/30/25.
//

#pragma once
#include <cstdint>

namespace Skater {
    struct Color {
        float R = 1.0;
        float G = 1.0;
        float B = 1.0;
        float A = 1.0;

        Color() : Color(1.0f, 1.0f, 1.0f, 1.0f) {}
        Color(const uint8_t red, const uint8_t green, const uint8_t blue) : Color(red / 255.0f, green / 255.0f, blue / 255.0f, 1.0) {}
        Color(const uint8_t red, const uint8_t green, const uint8_t blue, const uint8_t alpha) : Color(red / 255.0f, green / 255.0f, blue / 255.0f, alpha / 255.0f) {}

        Color(const float red, const float green, const float blue, const float alpha) : R(red), G(green), B(blue), A(alpha) {}

        static const Color AliceBlue;
        static const Color AntiqueWhite;
        static const Color Aqua;
        static const Color Aquamarine;
        static const Color Azure;
        static const Color Beige;
        static const Color Bisque;
        static const Color Black;
        static const Color BlanchedAlmond;
        static const Color Blue;
        static const Color BlueViolet;
        static const Color Brown;
        static const Color BurlyWood;
        static const Color CadetBlue;
        static const Color Chartreuse;
        static const Color Chocolate;
        static const Color Coral;
        static const Color CornSilk;
        static const Color CornflowerBlue;
        static const Color Crimson;
        static const Color Cyan;
        static const Color DarkBlue;
        static const Color DarkCyan;
        static const Color DarkGoldenrod;
        static const Color DarkGray;
        static const Color DarkGreen;
        static const Color DarkKhaki;
        static const Color DarkMagenta;
        static const Color DarkOliveGreen;
        static const Color DarkOrange;
        static const Color DarkOrchid;
        static const Color DarkRed;
        static const Color DarkSalmon;
        static const Color DarkSeaGreen;
        static const Color DarkSlateBlue;
        static const Color DarkSlateGray;
        static const Color DarkTurquoise;
        static const Color DarkViolet;
        static const Color DeepPink;
        static const Color DeepSkyBlue;
        static const Color DimGray;
        static const Color DodgerBlue;
        static const Color Firebrick;
        static const Color FloralWhite;
        static const Color ForestGreen;
        static const Color Fuchsia;
        static const Color Gainsboro;
        static const Color GhostWhite;
        static const Color Gold;
        static const Color Goldenrod;
        static const Color Gray;
        static const Color Green;
        static const Color GreenYellow;
        static const Color Honeydew;
        static const Color HotPink;
        static const Color IndianRed;
        static const Color Indigo;
        static const Color Ivory;
        static const Color Khaki;
        static const Color Lavender;
        static const Color LavenderBlush;
        static const Color LawnGreen;
        static const Color LemonChiffon;
        static const Color LightBlue;
        static const Color LightCoral;
        static const Color LightCyan;
        static const Color LightGoldenrodYellow;
        static const Color LightGreen;
        static const Color LightGrey;
        static const Color LightPink;
        static const Color LightSalmon;
        static const Color LightSeaGreen;
        static const Color LightSkyBlue;
        static const Color LightSlateGray;
        static const Color LightSteelBlue;
        static const Color LightYellow;
        static const Color Lime;
        static const Color LimeGreen;
        static const Color Linen;
        static const Color Magenta;
        static const Color Maroon;
        static const Color MediumAquamarine;
        static const Color MediumBlue;
        static const Color MediumOrchid;
        static const Color MediumPurple;
        static const Color MediumSeaGreen;
        static const Color MediumSlateBlue;
        static const Color MediumSpringGreen;
        static const Color MediumTurquoise;
        static const Color MediumVioletRed;
        static const Color MidnightBlue;
        static const Color MintCream;
        static const Color MistyRose;
        static const Color Moccasin;
        static const Color NavajoWhite;
        static const Color Navy;
        static const Color OldLace;
        static const Color Olive;
        static const Color OliveDrab;
        static const Color Orange;
        static const Color OrangeRed;
        static const Color Orchid;
        static const Color PaleGoldenrod;
        static const Color PaleGreen;
        static const Color PaleTurquoise;
        static const Color PaleVioletRed;
        static const Color PapayaWhip;
        static const Color PeachPuff;
        static const Color Peru;
        static const Color Pink;
        static const Color Plum;
        static const Color PowderBlue;
        static const Color Purple;
        static const Color Red;
        static const Color RosyBrown;
        static const Color RoyalBlue;
        static const Color SaddleBrown;
        static const Color Salmon;
        static const Color SandyBrown;
        static const Color SeaGreen;
        static const Color SeaShell;
        static const Color Sienna;
        static const Color Silver;
        static const Color SkyBlue;
        static const Color SlateBlue;
        static const Color Snow;
        static const Color SpringGreen;
        static const Color SteelBlue;
        static const Color Tan;
        static const Color Teal;
        static const Color Thistle;
        static const Color Tomato;
        static const Color Turquoise;
        static const Color Violet;
        static const Color Wheat;
        static const Color White;
        static const Color WhiteSmoke;
        static const Color Yellow;
        static const Color YellowGreen;
    };

    inline const Color Color::AliceBlue(240, 248, 255);
    inline const Color Color::AntiqueWhite(250, 235, 215);
    inline const Color Color::Aqua(0, 255, 255);
    inline const Color Color::Aquamarine(127, 255, 212);
    inline const Color Color::Azure(240, 255, 255);
    inline const Color Color::Beige(245, 245, 220);
    inline const Color Color::Bisque(255, 228, 196);
    inline const Color Color::Black(0, 0, 0);
    inline const Color Color::BlanchedAlmond(255, 235, 205);
    inline const Color Color::Blue(0, 0, 255);
    inline const Color Color::BlueViolet(138, 43, 226);
    inline const Color Color::Brown(165, 42, 42);
    inline const Color Color::BurlyWood(222, 184, 135);
    inline const Color Color::CadetBlue(95, 158, 160);
    inline const Color Color::Chartreuse(127, 255, 0);
    inline const Color Color::Chocolate(210, 105, 30);
    inline const Color Color::Coral(255, 127, 80);
    inline const Color Color::CornSilk(255, 248, 220);
    inline const Color Color::CornflowerBlue(100, 149, 237);
    inline const Color Color::Crimson(220, 20, 60);
    inline const Color Color::Cyan(0, 255, 255);
    inline const Color Color::DarkBlue(0, 0, 139);
    inline const Color Color::DarkCyan(0, 139, 139);
    inline const Color Color::DarkGoldenrod(184, 134, 11);
    inline const Color Color::DarkGray(169, 169, 169);
    inline const Color Color::DarkGreen(0, 100, 0);
    inline const Color Color::DarkKhaki(189, 183, 107);
    inline const Color Color::DarkMagenta(139, 0, 139);
    inline const Color Color::DarkOliveGreen(85, 107, 47);
    inline const Color Color::DarkOrange(255, 140, 0);
    inline const Color Color::DarkOrchid(153, 50, 204);
    inline const Color Color::DarkRed(139, 0, 0);
    inline const Color Color::DarkSalmon(233, 150, 122);
    inline const Color Color::DarkSeaGreen(141, 188, 143);
    inline const Color Color::DarkSlateBlue(72, 61, 139);
    inline const Color Color::DarkSlateGray(47, 79, 79);
    inline const Color Color::DarkTurquoise(0, 222, 209);
    inline const Color Color::DarkViolet(148, 0, 211);
    inline const Color Color::DeepPink(255, 20, 147);
    inline const Color Color::DeepSkyBlue(0, 191, 255);
    inline const Color Color::DimGray(105, 105, 105);
    inline const Color Color::DodgerBlue(30, 144, 255);
    inline const Color Color::Firebrick(178, 34, 34);
    inline const Color Color::FloralWhite(255, 250, 240);
    inline const Color Color::ForestGreen(34, 139, 34);
    inline const Color Color::Fuchsia(255, 0, 255);
    inline const Color Color::Gainsboro(220, 220, 220);
    inline const Color Color::GhostWhite(248, 248, 255);
    inline const Color Color::Gold(255, 215, 0);
    inline const Color Color::Goldenrod(218, 165, 32);
    inline const Color Color::Gray(128, 128, 128);
    inline const Color Color::Green(0, 128, 0);
    inline const Color Color::GreenYellow(173, 255, 47);
    inline const Color Color::Honeydew(240, 255, 240);
    inline const Color Color::HotPink(255, 105, 180);
    inline const Color Color::IndianRed(205, 92, 92);
    inline const Color Color::Indigo(75, 0, 130);
    inline const Color Color::Ivory(255, 255, 240);
    inline const Color Color::Khaki(240, 230, 140);
    inline const Color Color::Lavender(230, 230, 250);
    inline const Color Color::LavenderBlush(255, 240, 245);
    inline const Color Color::LawnGreen(124, 252, 0);
    inline const Color Color::LemonChiffon(255, 250, 205);
    inline const Color Color::LightBlue(173, 216, 230);
    inline const Color Color::LightCoral(240, 128, 128);
    inline const Color Color::LightCyan(224, 255, 255);
    inline const Color Color::LightGoldenrodYellow(250, 250, 210);
    inline const Color Color::LightGreen(144, 238, 144);
    inline const Color Color::LightGrey(211, 211, 211);
    inline const Color Color::LightPink(255, 182, 193);
    inline const Color Color::LightSalmon(255, 160, 122);
    inline const Color Color::LightSeaGreen(32, 178, 170);
    inline const Color Color::LightSkyBlue(135, 206, 250);
    inline const Color Color::LightSlateGray(119, 136, 153);
    inline const Color Color::LightSteelBlue(176, 196, 222);
    inline const Color Color::LightYellow(255, 255, 224);
    inline const Color Color::Lime(0, 255, 0);
    inline const Color Color::LimeGreen(50, 205, 50);
    inline const Color Color::Linen(250, 240, 230);
    inline const Color Color::Magenta(255, 0, 255);
    inline const Color Color::Maroon(128, 0, 0);
    inline const Color Color::MediumAquamarine(102, 205, 170);
    inline const Color Color::MediumBlue(0, 0, 205);
    inline const Color Color::MediumOrchid(186, 85, 211);
    inline const Color Color::MediumPurple(147, 112, 216);
    inline const Color Color::MediumSeaGreen(60, 179, 113);
    inline const Color Color::MediumSlateBlue(123, 104, 238);
    inline const Color Color::MediumSpringGreen(0, 15, 169);
    inline const Color Color::MediumTurquoise(72, 209, 204);
    inline const Color Color::MediumVioletRed(199, 21, 133);
    inline const Color Color::MidnightBlue(25, 25, 112);
    inline const Color Color::MintCream(245, 255, 250);
    inline const Color Color::MistyRose(255, 228, 225);
    inline const Color Color::Moccasin(255, 228, 181);
    inline const Color Color::NavajoWhite(255, 222, 173);
    inline const Color Color::Navy(0, 0, 128);
    inline const Color Color::OldLace(253, 245, 230);
    inline const Color Color::Olive(128, 128, 0);
    inline const Color Color::OliveDrab(107, 142, 35);
    inline const Color Color::Orange(255, 165, 0);
    inline const Color Color::OrangeRed(255, 69, 0);
    inline const Color Color::Orchid(218, 112, 214);
    inline const Color Color::PaleGoldenrod(238, 232, 170);
    inline const Color Color::PaleGreen(152, 251, 152);
    inline const Color Color::PaleTurquoise(175, 238, 238);
    inline const Color Color::PaleVioletRed(219, 112, 147);
    inline const Color Color::PapayaWhip(255, 239, 213);
    inline const Color Color::PeachPuff(255, 218, 185);
    inline const Color Color::Peru(205, 133, 63);
    inline const Color Color::Pink(255, 200, 203);
    inline const Color Color::Plum(221, 160, 221);
    inline const Color Color::PowderBlue(176, 224, 230);
    inline const Color Color::Purple(128, 0, 128);
    inline const Color Color::Red(255, 0, 0);
    inline const Color Color::RosyBrown(188, 143, 143);
    inline const Color Color::RoyalBlue(65, 105, 225);
    inline const Color Color::SaddleBrown(139, 69, 19);
    inline const Color Color::Salmon(250, 128, 114);
    inline const Color Color::SandyBrown(244, 164, 96);
    inline const Color Color::SeaGreen(46, 139, 87);
    inline const Color Color::SeaShell(255, 245, 238);
    inline const Color Color::Sienna(160, 82, 45);
    inline const Color Color::Silver(192, 192, 192);
    inline const Color Color::SkyBlue(135, 206, 235);
    inline const Color Color::SlateBlue(106, 90, 205);
    inline const Color Color::Snow(255, 250, 250);
    inline const Color Color::SpringGreen(0, 255, 127);
    inline const Color Color::SteelBlue(70, 130, 180);
    inline const Color Color::Tan(210, 180, 140);
    inline const Color Color::Teal(0, 128, 128);
    inline const Color Color::Thistle(216, 191, 216);
    inline const Color Color::Tomato(255, 99, 71);
    inline const Color Color::Turquoise(64, 224, 208);
    inline const Color Color::Violet(238, 130, 238);
    inline const Color Color::Wheat(245, 222, 179);
    inline const Color Color::White(255, 255, 255);
    inline const Color Color::WhiteSmoke(245, 245, 245);
    inline const Color Color::Yellow(255, 255, 0);
    inline const Color Color::YellowGreen(154, 205, 50);
}
